# Generated by Django 5.1.1 on 2024-09-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public (Anonymous users can see)'), ('authenticated', 'Authenticated users only'), ('private', 'Private (Only creator)')], default='private', max_length=13),
        ),
    ]
